---
#
# site.yml
#

- hosts: all
  remote_user: isucon
  roles:
    - role: common
      tags:
        - common
    - role: nginx
      tags:
        - nginx
    - role: mysql
      tags:
        - mysql

...
